update for pyro
Signed-off-by: Tim Harvey <tharvey@gateworks.com>

diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -1,7 +1,7 @@
 #!/bin/sh
 # -*- mode: shell-script; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 #
-# Copyright (C) 2012, 2013 O.S. Systems Software LTDA.
+# Copyright (C) 2012, 2013, 2016 O.S. Systems Software LTDA.
 # Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
 #
 # This program is free software; you can redistribute it and/or modify
@@ -29,19 +29,45 @@ PROGNAME="setup-environment"
 
 usage()
 {
-    echo -e "\nUsage: source $PROGNAME <build-dir>
-    <build-dir>: required option; specifies build directory location
+    echo -e "
+Usage: MACHINE=<machine> DISTRO=<distro> source $PROGNAME <build-dir>
+Usage:                                   source $PROGNAME <build-dir>
+    <machine>    machine name
+    <distro>     distro name
+    <build-dir>  build directory
 
-By default the script will setup MACHINE to be ventana. 
+The first usage is for creating a new build directory. In this case, the
+script creates the build directory <build-dir>, configures it for the
+specified <machine> and <distro>, and prepares the calling shell for running
+bitbake on the build directory.
 
-Supported machines: `ls sources/*/conf/machine/*.conf \
-| sed s/\.conf//g | sed -r 's/^.+\///' | xargs echo`
-
-To build for a machine listed above, run this script as:
-MACHINE=<machine> source $PROGNAME <build-dir>
-
-The script sets PARALLEL_MAKE & BB_NUMBER_THREADS to $NCPU
+The second usage is for using an existing build directory. In this case,
+the script prepares the calling shell for running bitbake on the build
+directory <build-dir>. The build directory configuration is unchanged.
 "
+
+    ls sources/*/conf/machine/*.conf > /dev/null 2>&1
+    ls sources/meta-freescale-distro/conf/distro/fslc-*.conf > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        echo -e "
+Supported machines: `echo; ls sources/*/conf/machine/*.conf \
+| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
+
+Supported Freescale's distros: `echo; ls sources/meta-freescale-distro/conf/distro/fslc-*.conf \
+| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
+
+Available Poky's distros: `echo; ls sources/poky/meta-poky/conf/distro/*.conf \
+| sed s/\.conf//g | sed -r 's/^.+\///' | xargs -I% echo -e "\t%"`
+
+Examples:
+
+- To create a new Yocto build directory:
+  $ MACHINE=imx6qsabresd DISTRO=fslc-framebuffer source $PROGNAME build
+
+- To use an existing Yocto build directory:
+  $ source $PROGNAME build
+"
+    fi
 }
 
 clean_up()
@@ -84,6 +110,12 @@ if [ "$(whoami)" = "root" ]; then
     echo "ERROR: do not use the BSP as root. Exiting..."
 fi
 
+if [ ! -e $1/conf/local.conf.sample ]; then
+    build_dir_setup_enabled="true"
+else
+    build_dir_setup_enabled="false"
+fi
+
 if [ -z "$MACHINE" ]; then
     MACHINE='ventana'
 fi
@@ -92,59 +124,42 @@ if [ -z "$PACKAGING" ]; then
     PACKAGING='ipk'
 fi
 
-# Check the machine type specified
-LIST_MACHINES=`ls -1 $CWD/sources/*/conf/machine`
-VALID_MACHINE=`echo -e "$LIST_MACHINES" | grep ${MACHINE}.conf$ | wc -l`
-if [ "x$MACHINE" = "x" ] || [ "$VALID_MACHINE" = "0" ]; then
-    echo -e "\nSPECIFIED AN INVALID MACHINE TYPE !"
-    usage && clean_up
+if [ "$build_dir_setup_enabled" = "true" ] && [ -z "$MACHINE" ]; then
+    usage
+    echo -e "ERROR: You must set MACHINE when creating a new build directory."
+    clean_up
     return 1
-else
-    echo "Configuring for ${MACHINE}"
 fi
 
 if [ -z "$SDKMACHINE" ]; then
     SDKMACHINE='i686'
 fi
 
-if [ -z "$DISTRO" ]; then
-    DISTRO='poky'
+if [ "$build_dir_setup_enabled" = "true" ] && [ -z "$DISTRO" ]; then
+    usage
+    echo -e "ERROR: You must set DISTRO when creating a new build directory."
+    clean_up
+    return 1
 fi
 
-OEROOT=sources/poky
-if [ -e sources/oe-core ]; then
-    OEROOT=sources/oe-core
+OEROOT=$PWD/sources/poky
+if [ -e $PWD/sources/oe-core ]; then
+    OEROOT=$PWD/sources/oe-core
 fi
 
-# Ensure all files in sources/base are kept in sync with project root
-updated=
-for f in $CWD/sources/base/*; do
-    file="$(basename $f)"
-    if [ "$file" = "conf" ] || echo $file | grep -q '~$'; then
-        continue
-    fi
+. $OEROOT/oe-init-build-env $CWD/$1 > /dev/null
 
-    if ! cmp -s "$file" "$f"; then
-        updated="true"
-        [ -e $file ] && chmod u+w $file
-        cp $f $file
-    fi
-done
-if [ "$updated" = "true" ]; then
-    echo "The project root content has been updated. Please run $0 again."
-    return
+# if conf/local.conf not generated, no need to go further
+if [ ! -e conf/local.conf ]; then
+    clean_up && return 1
 fi
-
-cd $OEROOT
-
-. ./oe-init-build-env $CWD/$1 > /dev/null
 
 # Clean up PATH, because if it includes tokens to current directories somehow,
 # wrong binaries can be used instead of the expected ones during task execution
 export PATH="`echo $PATH | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//'`"
 
 generated_config=
-if [ ! -e conf/local.conf.sample ]; then
+if [ "$build_dir_setup_enabled" = "true" ]; then
     mv conf/local.conf conf/local.conf.sample
 
     # Generate the local.conf based on the Yocto defaults
@@ -164,9 +179,6 @@ EOF
         -e "s,PACKAGE_CLASSES ?=.*,PACKAGE_CLASSES ?= 'package_$PACKAGING',g" \
         -i conf/local.conf
 
-    # add commerical license to allow gst-plugins-ugly
-    echo 'LICENSE_FLAGS_WHITELIST += "commercial"' >> conf/local.conf
-
     cp $TEMPLATES/* conf/
 
     for s in $HOME/.oe $HOME/.yocto; do
@@ -180,43 +192,57 @@ EOF
 fi
 
 # Handle EULA setting
-if [ -z "$EULA" ] && ! grep -q '^ACCEPT_FSL_EULA\s*=' conf/local.conf; then
-    EULA='ask'
+EULA_ACCEPTED=
+
+# EULA has been accepted already (ACCEPT_FSL_EULA is set in local.conf)
+if grep -q '^\s*ACCEPT_FSL_EULA\s*=\s*["'\'']..*["'\'']' conf/local.conf; then
+    EULA_ACCEPTED=1
 fi
 
-if [ "$EULA" = "ask" ]; then
+if [ -z "$EULA_ACCEPTED" ] && [ -n "$EULA" ]; then
+    # The FSL EULA is not set as accepted in local.conf, but the EULA
+    # variable is set in the environment, so we just configure
+    # ACCEPT_FSL_EULA in local.conf according to $EULA.
+    echo "ACCEPT_FSL_EULA = \"$EULA\"" >> conf/local.conf
+    EULA_ACCEPTED=1
+elif [ -n "$EULA_ACCEPTED" ]; then
+    # The FSL EULA has been accepted once, so ACCEPT_FSL_EULA is set
+    # in local.conf.  No need to do anything.
+    EULA_ACCEPTED=1
+else
+    # THE FSL EULA is not set as accepted in local.conf, and EULA is
+    # not set in the environment, so we need to ask user if he/she
+    # accepts the FSL EULA:
     cat <<EOF
 
-Some SoC depends on libraries and packages that are covered by
-Freescale EULA. To have the right to use those binaries in your images
-you need to read and accept the EULA that will be displayed.
+Some BSPs depend on libraries and packages which are covered by Freescale's
+End User License Agreement (EULA). To have the right to use these binaries in
+your images, you need to read and accept the following...
 
 EOF
 
     sleep 4
 
-    more -d $CWD/sources/meta-fsl-arm/EULA
+    more -d $CWD/sources/meta-freescale/EULA
     echo
-    while [ "$EULA" = "ask" ]; do
+    REPLY=
+    while [ -z "$REPLY" ]; do
         echo -n "Do you accept the EULA you just read? (y/n) "
         read REPLY
         case "$REPLY" in
             y|Y)
             echo "EULA has been accepted."
-            EULA="1"
+            echo "ACCEPT_FSL_EULA = \"1\"" >> conf/local.conf
+            EULA_ACCEPTED=1
             ;;
             n|N)
             echo "EULA has not been accepted."
-            EULA="0"
+            ;;
+            *)
+            REPLY=
             ;;
         esac
     done
-fi
-
-if grep -q '^ACCEPT_FSL_EULA\s*=' conf/local.conf; then
-    sed -i "s/^#*ACCEPT_FSL_EULA\s*=.*/ACCEPT_FSL_EULA = \"$EULA\"/g" conf/local.conf
-else
-    echo "ACCEPT_FSL_EULA = \"$EULA\"" >> conf/local.conf
 fi
 
 cat <<EOF
@@ -234,9 +260,9 @@ You can now run 'bitbake <target>'
 
 Common targets are:
     core-image-minimal
-    gateworks-image-test
+    gateworks-image-minimal
+    gateworks-image-multimedia
     gateworks-image-gui
-    fsl-image-multimedia
     meta-toolchain
     meta-toolchain-sdk
     adt-installer
@@ -246,16 +272,15 @@ EOF
 
 if [ -n "$generated_config" ]; then
     cat <<EOF
-Your build environemnt has been configured with:
+Your build environment has been configured with:
 
     MACHINE=$MACHINE
-    PACKAGING=$PACKAGING
     SDKMACHINE=$SDKMACHINE
     DISTRO=$DISTRO
-    EULA=$EULA
+    ACCEPT_FSL_EULA=$EULA_ACCEPTED
 EOF
 else
-    echo "Your configuration files at $1 has not been touched."
+    echo "Your configuration files at $1 have not been touched."
 fi
 
 clean_up
